### ISSUE TITLE
file upload error - netxcloud 22.2.3

### ISSUE THREAD

**Issue by tiandiyiqi** [e-alfred/flowupload#471]
Centos8 PHP8 Nextcloud 22.2.3

log:

[index] Error: Call to a member function mkdir() on null

POST /seacloud/index.php/apps/flowupload/upload
from 127.0.0.1 by admin at 2021-12-07T05:45:57+00:00

  | Exception: Call to a member function mkdir() on null/var/www/html/seacloud/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/html/seacloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/html/seacloud/lib/base.php - line 1006: OC\Route\Router->match()/var/www/html/seacloud/index.php - line 36: OC::handleRequest()造成的原因是 Error: Call to a member function mkdir() on null/var/www/html/seacloud/apps/flowupload/lib/Controller/UploadController.php - line 85: OC\Files\Filesystem::mkdir()/var/www/html/seacloud/lib/private/AppFramework/Http/Dispatcher.php - line 217: OCA\flowupload\Controller\UploadController->upload()/var/www/html/seacloud/lib/private/AppFramework/Http/Dispatcher.php - line 126: OC\AppFramework\Http\Dispatcher->executeController()/var/www/html/seacloud/lib/private/AppFramework/App.php - line 156: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/html/seacloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/html/seacloud/lib/base.php - line 1006: OC\Route\Router->match()/var/www/html/seacloud/index.php - line 36: OC::handleRequest()

**Comment by christoschronopoulos** [comment]
Unfortunately, it doesn't seem to be actively maintained. There are some issues that I described in other posts but I haven't received any feedback.

**Comment by stratege1401** [comment]
Debian  11.2 official, php7.4 official, nextcloud 22.2.3, flowupload 1.1.3

NOT WORKING.

`[no app in context] Info: Could not resolve OCA\DefaultGroup\Settings\AdminSection! Class OCA\DefaultGroup\Settings\AdminSection does not exist

GET /index.php/settings/admin/logging
from 192.168.1.254 by rodolphe.cahen@gmail.com at 2021-12-24T14:17:01+00:00`

**Comment by JonathanTreffler** [comment]
> Unfortunately, it doesn't seem to be actively maintained. There are some issues that I described in other posts but I haven't received any feedback.

It is maintained :). But it is hard to keep up with the frequent nextcloud updates.

**Comment by JonathanTreffler** [comment]
Are you on the Nextcloud 22 beta we provided ?

https://github.com/e-alfred/flowupload/issues/305#issuecomment-877785553

**Comment by stratege1401** [comment]
> Are you on the Nextcloud 22 beta we provided ?
> 
> [#305 (comment)](https://github.com/e-alfred/flowupload/issues/305#issuecomment-877785553)


No. 

N22.2.3 notifications show you push a new version. I updated this new version ... The beta did not work before...

**Comment by JonathanTreffler** [comment]
I can confirm that release 1.1.3 seems to be broken (at least on nextcloud 23).

I have debugged a bit and come closer to a fix, but don't have one yet. My time is very limited right now.
The problem is, that we use \OC\ APIs, wich are internal only, but as far as I know that was at least a few nextcloud versions ago the only solution for our usecase.
We should probably transition to using the OCP scope only.

**Comment by jason5545** [comment]
> I can confirm that release 1.1.3 seems to be broken (at least on nextcloud 23).
> 
> I have debugged a bit and come closer to a fix, but don't have one yet. My time is very limited right now. The problem is, that we use \OC\ APIs, wich are internal only, but as far as I know that was at least a few nextcloud versions ago the only solution for our usecase. We should probably transition to using the OCP scope only.

I can confirm that the beta version works on nextcloud 23

**Comment by ibboliver** [comment]
> I can confirm that the beta version works on nextcloud 23

On my nextcloud 23.0.0 only an empty content appears under the menu. The source of the html shows
```
...
<div id="content" class="app-flowupload" role="main">
    <div id="vue-content"></div>
</div>
...
```

**Comment by wreidlinger** [comment]
hi there,

my setup:
_Flow Upload 1.1.3
nextcloud: 23.0.2.1
nginx 1.20.2
mysql 10.3.32
php 8.0.16
ubuntu 20.04.4 LTS_

I can't upload any (small or big) file via the flowupload app. Attached you can see the log entry of the nginx webserver and the error in the nextcloud webinterface.

![error-nc-webinterface-flowupload-1](https://user-images.githubusercontent.com/100240865/155224607-39a3354c-7f14-4458-802a-c4cb0762aeb4.png)

![error-nc-webinterface-flowupload-2](https://user-images.githubusercontent.com/100240865/155224609-ec31a62b-5c98-4fd9-bf18-a5e5910933b1.png)


here the nextcloud log file:


```
sudo -u www /opt/plesk/php/8.0/bin/php ./occ log:watch

Error    index
Exception: Call to a member function file_exists() on null in file
'/var/www/vhosts/domain.com/cloud/lib/private/Files/Filesystem.php' line 678 
at 2022-02-22T21:47:58+00:00 

lib/private/AppFramework/Http/Dispatcher.php line 158                                                                                                                                                        
                                                                                                                                                                                                                                           
0. lib/private/AppFramework/App.php line 157                                                                                                                                                                 
OC\AppFramework\Http\Dispatcher->dispatch()                                                                                                                                                                                                         

1. lib/private/Route/Router.php line 302                                                                                                                                                                     
OC\AppFramework\App::main()                                                                                                                                                                                                         

2. lib/base.php line 1006                                                                                                                                                                                    
OC\Route\Router->match()                                                                                                                                                                                                         

3. index.php line 36                                                                                                                                                                                         
OC::handleRequest()                                                                                                                                                                                                         
                                                                                                                                                                                                                                           
Caused by Error: Call to a member function file_exists() on null at lib/private/Files/Filesystem.php line 678                                                                                                
                                                                                                                                                                                                                                           
0. apps/flowupload/lib/Controller/UploadController.php line 84                                                                                                                                               
OC\Files\Filesystem::file_exists()                                                                                                                                                                                                         

1. lib/private/AppFramework/Http/Dispatcher.php line 217                                                                                                                                                     
OCA\flowupload\Controller\UploadController->upload()                                                                                                                                                                                                         

2. lib/private/AppFramework/Http/Dispatcher.php line 126                                                                                                                                                     
OC\AppFramework\Http\Dispatcher->executeController()                                                                                                                                                                                                         

3. lib/private/AppFramework/App.php line 157                                                                                                                                                                 
OC\AppFramework\Http\Dispatcher->dispatch()                                                                                                                                                                                                         

4. lib/private/Route/Router.php line 302                                                                                                                                                                     
OC\AppFramework\App::main()                                                                                                                                                                                                         

5. lib/base.php line 1006                                                                                                                                                                                    
OC\Route\Router->match()                                                                                                                                                                                                         

6. index.php line 36                                                                                                                                                                                         
OC::handleRequest()   
```

Is there a workaround or known bug?
Please anyone can help.

**Comment by jason5545** [comment]
> Are you on the Nextcloud 22 beta we provided ?
> 
> [#305 (comment)](https://github.com/e-alfred/flowupload/issues/305#issuecomment-877785553)

Try the beta mentioned here.

**Comment by jason5545** [comment]
> hi there,
> 
> my setup: _Flow Upload 1.1.3 nextcloud: 23.0.2.1 nginx 1.20.2 mysql 10.3.32 php 8.0.16 ubuntu 20.04.4 LTS_
> 
> I can't upload any (small or big) file via the flowupload app. Attached you can see the log entry of the nginx webserver and the error in the nextcloud webinterface.
> 
> ![error-nc-webinterface-flowupload-1](https://user-images.githubusercontent.com/100240865/155224607-39a3354c-7f14-4458-802a-c4cb0762aeb4.png)
> 
> ![error-nc-webinterface-flowupload-2](https://user-images.githubusercontent.com/100240865/155224609-ec31a62b-5c98-4fd9-bf18-a5e5910933b1.png)
> 
> here the nextcloud log file:
> 
> ```
> sudo -u www /opt/plesk/php/8.0/bin/php ./occ log:watch
> 
> Error    index
> Exception: Call to a member function file_exists() on null in file
> '/var/www/vhosts/domain.com/cloud/lib/private/Files/Filesystem.php' line 678 
> at 2022-02-22T21:47:58+00:00 
> 
> lib/private/AppFramework/Http/Dispatcher.php line 158                                                                                                                                                        
>                                                                                                                                                                                                                                            
> 0. lib/private/AppFramework/App.php line 157                                                                                                                                                                 
> OC\AppFramework\Http\Dispatcher->dispatch()                                                                                                                                                                                                         
> 
> 1. lib/private/Route/Router.php line 302                                                                                                                                                                     
> OC\AppFramework\App::main()                                                                                                                                                                                                         
> 
> 2. lib/base.php line 1006                                                                                                                                                                                    
> OC\Route\Router->match()                                                                                                                                                                                                         
> 
> 3. index.php line 36                                                                                                                                                                                         
> OC::handleRequest()                                                                                                                                                                                                         
>                                                                                                                                                                                                                                            
> Caused by Error: Call to a member function file_exists() on null at lib/private/Files/Filesystem.php line 678                                                                                                
>                                                                                                                                                                                                                                            
> 0. apps/flowupload/lib/Controller/UploadController.php line 84                                                                                                                                               
> OC\Files\Filesystem::file_exists()                                                                                                                                                                                                         
> 
> 1. lib/private/AppFramework/Http/Dispatcher.php line 217                                                                                                                                                     
> OCA\flowupload\Controller\UploadController->upload()                                                                                                                                                                                                         
> 
> 2. lib/private/AppFramework/Http/Dispatcher.php line 126                                                                                                                                                     
> OC\AppFramework\Http\Dispatcher->executeController()                                                                                                                                                                                                         
> 
> 3. lib/private/AppFramework/App.php line 157                                                                                                                                                                 
> OC\AppFramework\Http\Dispatcher->dispatch()                                                                                                                                                                                                         
> 
> 4. lib/private/Route/Router.php line 302                                                                                                                                                                     
> OC\AppFramework\App::main()                                                                                                                                                                                                         
> 
> 5. lib/base.php line 1006                                                                                                                                                                                    
> OC\Route\Router->match()                                                                                                                                                                                                         
> 
> 6. index.php line 36                                                                                                                                                                                         
> OC::handleRequest()   
> ```
> 
> Is there a workaround or known bug? Please anyone can help.

> Are you on the Nextcloud 22 beta we provided ?
> 
> [#305 (comment)](https://github.com/e-alfred/flowupload/issues/305#issuecomment-877785553)

Try the beta mentioned here.

**Comment by wreidlinger** [comment]
Thanks @jason5545 
After removing flowupload plugin version 1.1.3 and installing and enabeling the beta version (1.1.2) from the [mentioned link/comment](https://github.com/e-alfred/flowupload/issues/305#issuecomment-877785553) it worked instantly. For installing the plugin by hand one has to unzip the folder in the /apps within the nextcloud root directory. Be aware to set the correct owner/group (same as all the other plugins/directories) the the /flowupload directory.

![Screenshot 2022-02-23 092621](https://user-images.githubusercontent.com/100240865/155299762-b0e48cd4-dbb3-42dc-8453-bec8be9dca24.png)

![Screenshot 2022-02-23 092708](https://user-images.githubusercontent.com/100240865/155299790-38cfcd26-6d95-4424-98c4-26b59531a2f7.png)

**Comment by HFranz** [comment]
Same error with 1.1.3 and Nextcloud 24.0.3 and 24.0.4.

`Exception: Call to a member function file_exists() on null in file '/var/www/nextcloud/nc/lib/private/Files/Filesystem.php' line 595 /var/www/nextcloud/nc/lib/private/AppFramework/App.php - line 172:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/nc/lib/private/Route/Router.php - line 298:
OC\AppFramework\App::main()
/var/www/nextcloud/nc/lib/base.php - line 1023:
OC\Route\Router->match()
/var/www/nextcloud/nc/index.php - line 36:
OC::handleRequest()
Exception: Call to a member function file_exists() on null in file '/var/www/nextcloud/nc/lib/private/Files/Filesystem.php' line 595 /var/www/nextcloud/nc/lib/private/AppFramework/App.php - line 172:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/nc/lib/private/Route/Router.php - line 298:
OC\AppFramework\App::main()
/var/www/nextcloud/nc/lib/base.php - line 1023:
OC\Route\Router->match()
/var/www/nextcloud/nc/index.php - line 36:
OC::handleRequest()`

`Verursacht durch Error: Call to a member function file_exists() on null
/var/www/nextcloud/nc/apps/flowupload/lib/Controller/UploadController.php - line 84:
OC\Files\Filesystem::file_exists()
/var/www/nextcloud/nc/lib/private/AppFramework/Http/Dispatcher.php - line 225:
OCA\flowupload\Controller\UploadController->upload()
/var/www/nextcloud/nc/lib/private/AppFramework/Http/Dispatcher.php - line 133:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/nc/lib/private/AppFramework/App.php - line 172:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/nc/lib/private/Route/Router.php - line 298:
OC\AppFramework\App::main()
/var/www/nextcloud/nc/lib/base.php - line 1023:
OC\Route\Router->match()
/var/www/nextcloud/nc/index.php - line 36:
OC::handleRequest()`

**Comment by ShadabFaiz** [comment]
> Thanks @jason5545 After removing flowupload plugin version 1.1.3 and installing and enabeling the beta version (1.1.2) from the [mentioned link/comment](https://github.com/e-alfred/flowupload/issues/305#issuecomment-877785553) it worked instantly. For installing the plugin by hand one has to unzip the folder in the /apps within the nextcloud root directory. Be aware to set the correct owner/group (same as all the other plugins/directories) the the /flowupload directory.
> 
> ![Screenshot 2022-02-23 092621](https://user-images.githubusercontent.com/100240865/155299762-b0e48cd4-dbb3-42dc-8453-bec8be9dca24.png)
> 
> ![Screenshot 2022-02-23 092708](https://user-images.githubusercontent.com/100240865/155299790-38cfcd26-6d95-4424-98c4-26b59531a2f7.png)

how did you installed the app ?
I download the zip that was mentioned unpacked it in `/var/snap/nextcloud/current/nextcloud/extra-apps/flowupload/`.
Tried to install the packages's dependencies, but it seems al lthe pacakges are deprecated.
Then duing installation, got the error:
```bash
npm ERR! code 7
npm ERR! path /var/snap/nextcloud/37720/nextcloud/extra-apps/flowupload/node_modules/iltorb
npm ERR! command failed
npm ERR! command sh -c node ./scripts/install.js || node-gyp rebuild
npm ERR! info install installing standalone, skipping download.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@20.7.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.11.3 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v20.7.0/node-v20.7.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.7.0/node-v20.7.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v20.7.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.7.0/SHASUMS256.txt
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
npm ERR! gyp ERR! stack     at createConfigFile (/var/snap/nextcloud/37720/nextcloud/extra-apps/flowupload/node_modules/node-gyp/lib/configure.js:117:21)
npm ERR! gyp ERR! stack     at /var/snap/nextcloud/37720/nextcloud/extra-apps/flowupload/node_modules/node-gyp/lib/configure.js:84:9
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:189:23)
npm ERR! gyp ERR! System Linux 5.15.120-1-MANJARO
npm ERR! gyp ERR! command "/home/server/.nvm/versions/node/v20.7.0/bin/node" "/var/snap/nextcloud/37720/nextcloud/extra-apps/flowupload/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /var/snap/nextcloud/37720/nextcloud/extra-apps/flowupload/node_modules/iltorb
npm ERR! gyp ERR! node -v v20.7.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! Node-gyp failed to build your package.
npm ERR! gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
```
